# Generated by Django 4.1.1 on 2022-11-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=40)),
                ('cuerpo', models.CharField(max_length=256)),
                ('fecha', models.DateField()),
                ('archivo', models.FileField(upload_to='')),
            ],
        ),
    ]
